### ISSUE TITLE
Local offerings filter is gone

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#10]
Somehow, there is no option to filter by local offerings anymore:
<img src="https://github.com/kulturpass-de/kulturpass-app/assets/67682506/742e5137-ce16-415c-9f6e-27fc98a3b75e" width="300">

**Comment by thomasaugsten** [comment]
We are still working on to improve the local search

**Comment by Ein-Tim** [comment]
@thomasaugsten Can you confirm that this feature works now and will continue to work?

**Comment by thomasaugsten** [comment]
Partially we unlock spatial filtering step by step but the specific filter is now active yes.
