### ISSUE TITLE
Too many books

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#12]
Due to the amount of books in the system, the app is promoting books way too much. I wouldn't have a problem with this if the books were interesting, but there are also so many books which are only relevant for a minority of people, for example when searching for "Samra" the top result is "Konzipierung eines Akzeptanzmodells für die private Nutzung von Dienstleistungen in einer Smart City sowie Ableitung von Handlungsempfehlungen zur Implementierung für Städte in Baden-Württemberg", which is, just like so many other books in the system, very domain specific and expert literature which is not relevant for the target audience. 

I see 3 options how to handle this: 
Books should be
a) removed and only be visible if the user searches for them
b) moved to their own category and be only shown there
c) their visibility should be reduced, not only in the search but only when pressing "Auf gut Glück" on the "Für dich" tab

**Comment by Ein-Tim** [comment]
@thomasaugsten What do you think about the idea of making the chance to see a book when pressing "Auf gut Glück" equally high as seeing another offering? 

Has the consumer shown any interest to change this, actually?

**Comment by thomasaugsten** [comment]
We are focusing at the moment to rework the home page to show more fitting offerings

**Comment by Ein-Tim** [comment]
Both the homepage and the search page got much better, however, the search is still basically useless without using filters, as no matter which term you search, there will be at least 20 books that match this term and they all will be shown.

**Comment by thomasaugsten** [comment]
Thank you for your positive feedback on our adjustments. Unfortunately, we currently have no available development resources for further improvements. We hope that we will be able to optimize the function in the future.

**Comment by Ein-Tim** [comment]
Also fixed. Thanks!
