### ISSUE TITLE
Remove Facebook Flipper Tracker

### ISSUE THREAD

**Issue by genofire** [kulturpass-de/kulturpass-app#14]
Please do not surveillance us and submit this data to US-Companies

See report:
https://reports.exodus-privacy.eu.org/en/reports/de.bkm.kulturpass/latest/

Description of the Tracker
https://reports.exodus-privacy.eu.org/en/trackers/392/

i believe it is needed for #1

**Comment by thomasaugsten** [comment]
The tool is not active in the relase build but we are working on to remove every reference in the release build and will provide an updated version as soon as possible.

**Comment by thomasaugsten** [comment]
Flipper References are removed in the release build
