### ISSUE TITLE
Remove Microsoft Visual Studio App Center Crashes

### ISSUE THREAD

**Issue by genofire** [kulturpass-de/kulturpass-app#15]
Please do not surveillance us and submit this data to US-Companies

See report:
https://reports.exodus-privacy.eu.org/en/reports/de.bkm.kulturpass/latest/

Description of the Tracker
https://reports.exodus-privacy.eu.org/en/trackers/238/

i believe it is needed for #1

**Comment by thomasaugsten** [comment]
Thanks for the hint we will investigate the issue

**Comment by thomasaugsten** [comment]
App Center Crash Reports are removed
