### ISSUE TITLE
What exception does the app show in case of a deactivated online function of the identity card?

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#16]
The title says it all. I'm asking because after writing with some users on Twitter I have the feeling that if the online function is deactivated the app also shows the timeout error and no other, specific error (see https://twitter.com/azadeuw/status/1669053079377829901?s=46&t=bmiC_2D8aUAJ5oyEs2jqBA & https://twitter.com/spiderfabii/status/1669057450241081348?s=20)

**Comment by thomasaugsten** [comment]
The exception should be
card?.deactivated === true
AA2_CARD_DEACTIVATED
"Dein Online-Ausweis ist deaktiviert und kann nicht zur Identifikation verwendet werden. Bitte nutze die AusweisApp2 für mehr Informationen.",

**Comment by Ein-Tim** [comment]
@thomasaugsten Please make sure that this is actually the error that's shown in this case and not the timeout one, as I have reports saying that it's showing the timeout one.

**Comment by Ein-Tim** [comment]
See also https://github.com/kulturpass-de/kulturpass-app/issues/9#issuecomment-1592409144

**Comment by Ein-Tim** [comment]
Okay this will be fixed in version 1.0.3, see https://github.com/kulturpass-de/kulturpass-app/issues/9#issuecomment-1593490694.

**Comment by Ein-Tim** [comment]
I confirmed myself that a deactivated Onlinefunktion causes the Timeout error. I hope that https://github.com/kulturpass-de/kulturpass-app/releases/tag/v1.0.3 fixes this.

**Comment by Ein-Tim** [comment]
@thomasaugsten Can you confirm that the issue has been fixed which caused the timeout error to show up when the "Online Ausweisfunktion" was disabled? If you can confirm, feel free to close this issue.

**Comment by thomasaugsten** [comment]
Exactly the specific timeout text is improved to inform the user and in 1.0.4 we introduce a immediately detection of deactivated id cards
