### ISSUE TITLE
AA2_INIT_ERROR

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#17]
I have a user report on Twitter (https://twitter.com/nora_1d_hp/status/1669010538410528773?s=46&t=bmiC_2D8aUAJ5oyEs2jqBA) reporting that for him scanning the ID card fails with the error which can be seen in this screenshot:

![image](https://github.com/kulturpass-de/kulturpass-app/assets/67682506/d029d298-fb4f-4c5b-8670-3e69d7142711)

**Comment by thomasaugsten** [comment]
Please test if a restart of the device is fixing this

**Comment by Ein-Tim** [comment]
@thomasaugsten This doesn't work: https://twitter.com/nora_1d_hp/status/1669424283012026377?s=20

**Comment by thomasaugsten** [comment]
Does she already mentioned the exact iPhone device and iOS version?

**Comment by Ein-Tim** [comment]
@thomasaugsten I will check that and come back to you

**Comment by Ein-Tim** [comment]
@thomasaugsten ![image](https://github.com/kulturpass-de/kulturpass-app/assets/67682506/ee2c560f-7b94-465e-af5e-40e5b6001418)

**Comment by Ein-Tim** [comment]
@thomasaugsten Galaxy A13 is the device and I pointed the user to the AusweisApp2

**Comment by Ein-Tim** [comment]
Closing due to missing feedback from the user.

**Comment by thomasaugsten** [comment]
With the A13 you have to identificate via Browser and Website https://storefront.prod.kulturpass.de/
Because the device is not supported by the AA2 SDK.


- Install AusweisApp2 on your phone
- Open https://storefront.prod.kulturpass.de/
- Register, Login and Identify
- The Browser will open AusweisApp2 for identification

**Comment by Ein-Tim** [comment]
@thomasaugsten This should be added in-app.
