### ISSUE TITLE
App and website randomly log out

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#18]
I noticed that both the app and the website sometimes randomly log me out and ask me to re-enter my mail and password. This isn't necessary and doesn't add any new layer of security, so this should be fixed.

Here's a screenshot depicting the error message that's shown in this case:
![Bildschirmfoto 2023-06-15 um 21 22 01](https://github.com/kulturpass-de/kulturpass-app/assets/67682506/4c544500-6579-4787-80f0-28c32ff06d85)

**Comment by Ein-Tim** [comment]
Here's a screenshot from within the app: 
![image](https://github.com/kulturpass-de/kulturpass-app/assets/67682506/ecd6fbd7-0787-4fcd-a30e-4c0b80a7157a)

**Comment by thomasaugsten** [comment]
The website should logout after 12h or browser closing. Do you see it often than this on the desktop website.

**Comment by Ein-Tim** [comment]
@thomasaugsten I'll try to keep track of the time the next time, but why is actually done? For security reasons?

**Comment by Ein-Tim** [comment]
@thomasaugsten Could you just confirm whether this is the intended behavior (security reasons (only thing I could imagine would be to make selling accounts harder)) or if that's a bug?

**Comment by fynngodau** [comment]
The duplicate text "signed out" and "session cancelled" from the screenshot is not optimal. Also, the text "cancelled" sounds like an error. If it is intentional, it should be "expired" and should not display in red.

**Comment by thomasaugsten** [comment]
The App  should not logout automatically we checking this at the moment.

**Comment by Ein-Tim** [comment]
@thomasaugsten I checked the website on Safari:
First use today: 15:30h
Now (21:30h) it asks me to log in again. That's not 12h.

**Comment by Ein-Tim** [comment]
That's better now.
