### ISSUE TITLE
"Vorlieben Anpassen" should have back button

### ISSUE THREAD

**Issue by timokoenig** [kulturpass-de/kulturpass-app#19]
The page "Vorlieben Anpassen" in the tab "Profil" is being pushed but shows a close button instead of the back button.

This only appears to be on that one screen. The other screens correctly show the back button to go back to the profile.

<img src="https://github.com/kulturpass-de/kulturpass-app/assets/4365095/2087deb5-b878-4339-88e2-ab0fc4a61fa8" width="300" />

**Comment by thomasaugsten** [comment]
The intention was to make it clear the user has to save here or cancel the change in Vorlieben and Profil anpassen

**Comment by Ein-Tim** [comment]
If this is a wont fix the corresponding label should be applied and this issue closed.
