### ISSUE TITLE
Fatal error when building the app

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#2]
I manged to get to the point where I can use Xcode to build the iOS app on my Mac, however, there the app only opens with this screen:

<img src="https://github.com/kulturpass-de/kulturpass-app/assets/67682506/0db0a7fe-5eb6-46c3-b59b-75824cb2ce88" width="300">

Here's the stack trace:

```
src/services/environment-configuration/environment-configuration.ts: /Users/tim/GitHub/kulturpass-de/kulturpass-app/src/services/environment-configuration/environment-configuration.ts: ENOENT: no such file or directory, open '/Users/tim/GitHub/kulturpass-de/kulturpass-app/src/services/environment-configuration/environment-configuration.yaml'

RCTFatal
__28-[RCTCxxBridge handleError:]_block_invoke
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_drain
_dispatch_main_queue_callback_4CF
__CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
__CFRunLoopRun
CFRunLoopRunSpecific
GSEventRunModal
-[UIApplication _run]
UIApplicationMain
main
start_sim
0x0
0x0
```

What can I do to resolve this issue?

**Comment by thomasaugsten** [comment]
You need a valid environment-configuration.yaml where all systems are references
We will provide the productive environment-configuration.yaml at go-live

**Comment by Ein-Tim** [comment]
Thanks for your fast response! I assume it is not planned to provide some sort of test configuration for the community in the meantime (between now and go-live)?

**Comment by Ein-Tim** [comment]
- I provided PR #3 to add this information to the README file
