### ISSUE TITLE
Loading Indicator is pixelated

### ISSUE THREAD

**Issue by timokoenig** [kulturpass-de/kulturpass-app#20]
The loading indicator seems to be in the wrong size and therefore appears very pixelated.

Device: iPhone 14 Pro Max

<img src="https://github.com/kulturpass-de/kulturpass-app/assets/4365095/0711705e-4384-432f-bb39-4005ffb0d20b" width="300" />

**Comment by thomasaugsten** [comment]
Thanks for the feedback we will improve the quality of the spinner

**Comment by thomasaugsten** [comment]
Loading indicator should be improved
