### ISSUE TITLE
Improve the search feature

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#22]
The search feature of the KulturPass is, to put it friendly, off. For example, when I search for "Kino am Olympiasee München" ([link to search](https://storefront.prod.kulturpass.de/search/Kino%20am%20Olympiasee%20München?postalCode=81373&query=Kino%20am%20Olympiasee%20München:relevance)) in the app, the app displays these results: 
![Bildschirmfoto 2023-06-17 um 20 07 32](https://github.com/kulturpass-de/kulturpass-app/assets/67682506/38805c03-59da-4548-9eba-c41668c2eec4)

These search results are basically useless, due to the amount of books that are related to the words "Kino", "am", "Olympiasee" & "München". Only by using the "Kino" filter, we can get a useful search result ([link to search with filter](https://storefront.prod.kulturpass.de/search/Kino%20am%20Olympiasee%20München?postalCode=81373&query=Kino%20am%20Olympiasee%20München:relevance:topCategory:cinema)).

But still, the actual Kino am Olympiasee in Munich ([link to website ](https://kinoamolympiasee.de)) can't be found. I confirmed that the cinema actually participates by writing them a mail, and I got the feedback that they are part of it. I can't find their offerings anywhere on your platform. 

Don't get me wrong, this could be a one-off problem here, but there are more and more examples out there (just search for "Kino München" and wonder why you get results for cinemas in Berlin), so this is not a support request but rather an enhancement request to improve the search feature.

**Comment by Ein-Tim** [comment]
Another example. The Süddeutsche Zeitung (SZ) is [reporting](https://www.sueddeutsche.de/bayern/kulturpass-tipps-muenchen-bayern-1.5957307) that I can visit the "Pinakothek der Moderne" & "Alte Pinakothek" in Munich with the KulturPass, but I can't find them via the in-app search feature. So either the SZ is just reporting wrong things or the search is just really bad.
I think this is also related to #12.

**Comment by Ein-Tim** [comment]
@thomasaugsten Any update on this? The situation hasn't really improved.

**Comment by thomasaugsten** [comment]
Thank you for your positive feedback on our adjustments. Unfortunately, we currently have no available development resources for further improvements. We hope that we will be able to optimize the function in the future.

**Comment by Ein-Tim** [comment]
Latest update really improved the search! Considering this as solved.
