### ISSUE TITLE
Improve swipe to close on iOS

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#24]
The swipe to close action under iOS is somehow strange, I would expect the whole picture to be the area where I can swipe down to close, and not only the very top of it.

Here's a screenrecording of the problem:

https://github.com/kulturpass-de/kulturpass-app/assets/67682506/536701c5-80dc-435d-9334-250703f52e8b

**Comment by Ein-Tim** [comment]
@thomasaugsten Is this the intended behaviour? If yes this is not consistent with other iOS (native) apps (like the app store).

**Comment by thomasaugsten** [comment]
Yes, it is the correct behavior, though it is not consistent with other native iOS apps. For technical reasons, we cannot implement it a different way.
