### ISSUE TITLE
Alle Favoriten sind auf einmal weg.

### ISSUE THREAD

**Issue by sami155** [kulturpass-de/kulturpass-app#25]
Ich war einige Wochen nicht in der App drinnen, und jetzt sind einfach alle meine mit Favoriten markierten Sachen weg.

**Comment by Ein-Tim** [comment]
Ich kann das bestätigen, glaube das hängt mit dem Update auf Version 1.1.0 zusammen.

**Comment by Ein-Tim** [comment]
@thomasaugsten Wenn die App ohne Internet geöffnet wird verschwinden alle Favoriten und kommen auch mit Internet nicht wieder zurück.

**Comment by thomasaugsten** [comment]
Ich kann es so nicht reproduzieren. Kannst du ein Video davon erstellen?

**Comment by Ein-Tim** [comment]
@thomasaugsten vorhin hatte ich das Problem. Jetzt tritt es nicht mehr auf. Ich probiere es weiterhin zu reproduzieren und melde mich wenn erfolgreich mit Video hier.
