### ISSUE TITLE
Reservierung nicht stornierbar

### ISSUE THREAD

**Issue by Binozo** [kulturpass-de/kulturpass-app#26]
Laut der offiziellen Kulturpass Seite sind Reservierungen mit dem Status "noch nicht angenommen" oder "Reservierung wird bearbeitet" in der App stornierbar.
[Quelle](https://service.kulturpass.de/help/de-de/47-stornierung/99-reservierungen-stornieren)

Nun habe ich kürzlich ein Buch reservieren lassen. Mir ist aber aufgefallen dass ich das Buch ausversehen in deutscher Sprache anstatt auf Englisch bestellt habe.

Nun suche ich vergeblich den "Bestellung stornieren" Button.

Dieser ist weder im Web, noch in der App zu finden
![image](https://github.com/kulturpass-de/kulturpass-app/assets/70137898/0c1e4527-c175-48a3-88d0-429177c744f6)

**Comment by Ein-Tim** [comment]
Du kannst auf jeden Fall in diesem Fall die Buchhandlung kontaktieren und darum bitten, dass sie deine Reservierung nicht annehmen. Dann für die Bestellung storniert. Warum es den Button nicht gibt, das ist eine gute Frage.

**Comment by Binozo** [comment]
Der Status hat sich gerade eben zu "Reservierung wird bearbeitet " geändert und ich konnte plötzlich doch stornieren. Komisch 🤔

**Comment by Binozo** [comment]
@thomasaugsten Ich denke nicht dass es richtig ist diesen Issue zu closen, weil das Problem ja immernoch besteht.

Bei mir hat sich der Status geändert, deswegen konnte ich stornieren. Aber bei dem vorherigen Status, wie es auch auf der [offiziellen Seite](https://service.kulturpass.de/help/de-de/47-stornierung/99-reservierungen-stornieren) steht, müsste es auch stornierbar sein.

### Reservierungen mit dem Status “_noch nicht angenommen_” oder “Reservierung wird bearbeitet” stornieren

> Befindet sich Deine Reservierung in dem Status “noch nicht angenommen” oder “Reservierung wird bearbeitet”, hast Du die Möglichkeit, diese Reservierung per Klick zu stornieren. Dazu gehst Du in den Bereich “Reservierungen”, “reserviert” und klickst auf die jeweilige Bestellung. Dir wird nun unten der Button “Stornierung” angezeigt. Dort klickst Du drauf und bestätigst die Stornierung mit einem Klick auf “Bestellung stornieren”.

Schade, verwirrt nur die User

**Comment by thomasaugsten** [comment]
Danke für den Hinweis wir werden die Anzeige noch verbessern das klar wird, dass die Reservierung gerade erstellt wird und noch nicht stornierbar ist.
