### ISSUE TITLE
KulturPass sometimes shows offerings in the past

### ISSUE THREAD

**Issue by Ein-Tim** [kulturpass-de/kulturpass-app#27]
I noticed that the KulturPass sometimes shows offerings in the past. That doesn't make sense and the app/website should only show stuff that's going to happen in the future. 

Here's a screenshot: 
![062D9FED-EE80-4E52-978B-D325EA0D4B86_1_102_o](https://github.com/kulturpass-de/kulturpass-app/assets/67682506/cc1ff199-38e2-44e1-9416-54a0aba92ce9)

**Comment by thomasaugsten** [comment]
Old offers should be removed from the catalog

**Comment by Ein-Tim** [comment]
@thomasaugsten But who is responsible for this and who makes sure that actually happens?

**Comment by thomasaugsten** [comment]
The seller is responsible for his offers and that they up to date
