### ISSUE TITLE
Identification impossible 

### ISSUE THREAD

**Issue by Luke1505** [kulturpass-de/kulturpass-app#5]
Every Time I want to identify for the KulturPass App i get this error ![Screenshot_20230614-063530.png](https://github.com/kulturpass-de/kulturpass-app/assets/64462934/f2b4da58-ffed-417d-aa2b-ac1f75c61f4c)

Device: Google Pixel 7 Pro 
Software: Android 14

**Comment by thomasaugsten** [comment]
Thank you for the feedback. The problem will be fixed with the app version 1.0.1. We expect the version to be released by Google in 2-3 days. We would ask you to try the identification again then.

**Comment by Luke1505** [comment]
Okay thanks, is there no way I could get it quicker beacause I'd like to use the KulturPass already ?

**Comment by thomasaugsten** [comment]
You can provide me the mail of your PlayStore Account via mail and you can pretest the new version.

thomas.augsten@sap.com

**Comment by Luke1505** [comment]
Thanks you it works now
