### ISSUE TITLE
Identifizierung nicht möglich.

### ISSUE THREAD

**Issue by sami155** [kulturpass-de/kulturpass-app#6]
Wenn ich mich identifizieren will, kommt jedesmal der Fehler "AA2_Timeout" in der Kulturpass App für Android.

Hier die Fehlermeldung vom System nach paar mal Abstürzen:

```
java.lang.UnsatisfiedLinkError: No implementation found for
java.lang.String com.governikus.ausweisapp2.AidIBinder.res
etValidSessionID() (tried Java_com_governikus_ausweisapp2
AidIBinder _ resetValidSessionID and Java_com_governikus_
ausweisapp2_AidlBinder_resetValidSessionID
at
com.governikus.ausweisapp2. AidlBinder.resetValidSessionID
(Native Method)
at
com.governikus.ausweisapp2.AidIBinder.connectSdk(AidBin
derjava:68)
at
com.governikus.ausweisapp2.lAusweisApp2Sdk$Stub.onTra
nsact(AusweisApp2Sdk.java:70)
at
android.os.Binder.execTransactInternal(Binder.java:1316)
at android.os.Binder.execTransact(Binder.java:1280)
```

**Comment by thomasaugsten** [comment]
Danke für das Feedback. Das Problem wird mit der App Version 1.0.1 behoben sein. Wir rechnen damit, dass die Version in 2-3 Tagen von Google freigegeben. Wir würden dich bitten dann die Identifikation erneut zu probieren.

**Comment by RobinSchfr** [comment]
Hallo, ich gib auch gerne Feedback.
Die Version 1.0.1 ist jetzt online, also App aktualisiert und getestet.
Ich kam diesmal im Identifikationsprozess zwei Schritte weiter, als ich jedoch auf Starten geklickt habe, nachdem ich mein Galaxy A51 auf meinen Ausweis gelegt habe, kam bei mehrmaligen Versuchen jedesmal der Fehler "AA2_Timeout". Es kam allerdings immer, als ich mein Handy auf dem Ausweis gelegt habe ein Signalton, deshalb geh ich davon aus, dass der NFC-Chip prinzipiell erkannt wurde.

**Comment by thomasaugsten** [comment]
Hast du den Ausweis flach hingelegt und das Handy darauf und nach dem ersten Erkennen das Gerät nicht mehr bewegt?

**Comment by RobinSchfr** [comment]
Ja ich habe es genau so gemacht wie es in den Anweisungen beschrieben ist und ich habe es nicht nur einmal probiert.

**Comment by CaptainSharky** [comment]
Genau das gleiche passiert bei mir. Zudem habe ich mich auch versucht über Web (auf dem Handy) anzumelden und das geht auch nicht, da steht nur, dass die AusweisApp2 nicht installiert ist obwohl diese installiert ist.

**Comment by thomasaugsten** [comment]
@CaptainSharky 

Welche Gerät verwendest du. Wieviel Sekunden vergehen bis der Timeout Fehler kommt. 

AusweisApp2 via Web funktioniert nur mit dem Desktop/Pc Programm und einem Desktop Browser.

**Comment by CaptainSharky** [comment]
@thomasaugsten ungefähr 20 Sekunden dauert es bis zum Timeout und ich benutze ein Samsung Galaxy S20 Plus.
![Screenshot_20230614_121623_Google Play Store.jpg](https://github.com/kulturpass-de/kulturpass-app/assets/47027824/86e21a6b-cf99-48e6-a49c-fdb2ff71e155)
