### ISSUE TITLE
Identifizierung auch bei Appversion 1.0.1 nicht möglich

### ISSUE THREAD

**Issue by pugnoxi** [kulturpass-de/kulturpass-app#9]
Der Identifizierungsprozess ist nach dem Appupdate auf Version 1.0.1 auf Android immernoch nicht möglich. Die App kommt zwar nun zwar 2 Bildschirme weiter (Welche Infos werden gelesen?, ...), aber der Ausweis wird mit gleichem Fehler zwar erkannt (Vibration beim dranhalten) aber halt nicht hinzufügt (AA2_TIMEOUT).

**Comment by RobinSchfr** [comment]
1 zu 1 das gleiche Problem auch bei mir

**Comment by Ein-Tim** [comment]
Könnt ihr es bitte nochmal probieren, nachdem ihr die App neu gestartet habt? Das hat gerade bei zwei anderen, mit denen ich auf Twitter geschrieben habe, geholfen.

**Comment by pugnoxi** [comment]
> 

funktioniert leider nicht

**Comment by CaptainSharky** [comment]
eine Fehlermöglichkeit weniger

**Comment by thomasaugsten** [comment]
Bitte mich via Mail mit dem PlayStore Account kontaktieren wer Interesse hat eine neue Version zu testen
thomas.augsten@sap.com

**Comment by Ein-Tim** [comment]
@thomasaugsten 

Sind nun auch viele iOS Nutzer auf Twitter die nun von Problemen berichten, entweder mit Timeout Meldungen oder AA2_INIT_ERROR

**Comment by Ein-Tim** [comment]
Auf Twitter nun immer mehr und mehr Berichte darüber, dass es in der AusweisApp2 klappt, in der KulturPass App aber nicht.
Wurde dafür schon der Fehler gefunden?

**Comment by Ein-Tim** [comment]
@pugnoxi & @CaptainSharky Seid ihr euch sicher, dass ihr die Online Funktion an eurem Perso aktiviert habt? Ihr könnt das mit der AusweisApp2 nachschauen.

**Comment by pugnoxi** [comment]
@Ein-Tim Hi! Hab gerade nachgeschaut, Ausweis ist nicht aktiviert. 
Vorschlag: Genau das als Error-Meldung hinschreiben und nicht AA2_Timeout ;)

**Comment by Ein-Tim** [comment]
@pugnoxi Dachte ich es mir doch :) 
Habe das in #16 gemeldet.

**Comment by Ein-Tim** [comment]
@thomasaugsten Gibts ne Timeline wann das Problem behoben sein wird? Oder sind das hier verschiedenste Fehlerursache die alle in den timeout Fehler münden?

**Comment by thomasaugsten** [comment]
Wir gehen davon aus das alle Timeouts nach dem Akzeptieren auf eine deaktivierte OnlineFunktion zurückzuführen sind.
Wir werden die Fehlerbeschreibung verbessern und erwarten ein Release morgen.
Wir arbeiten aber weiter an der Verbesserung des Prozess

**Comment by Ein-Tim** [comment]
Auf Twitter gibt es kaum noch Berichte über diesen Fehler, ich vermute er wurde behoben.
@pugnoxi & @RobinSchfr  Wie sieht es bei euch aus?

**Comment by RobinSchfr** [comment]
@Ein-Tim 
Ja, es lag tatsächlich an der deaktivierten Online Funktion bzw. an der irreführenden Fehlermeldung.

**Comment by thomasaugsten** [comment]
Die Fehlermeldung für deaktivierte Ausweise wurde verbessert und eine Hilfestellung gegeben wie man sie aktivieren kann.
